"""Visual Bible — LLM-generated visual direction for an entire video.

A *visual bible* is a structured JSON blueprint that describes the visual
universe, protagonist, recurring elements, and per-scene visual concepts
for a single video.  It is generated by a second LLM call that analyses
the completed script.

Phase 3 integrates the visual bible into the AI prompt pipeline so that
every generated image shares:
  - A consistent visual universe (time period, location, aesthetic).
  - A stable protagonist description (when the video features a person).
  - Recurring visual motifs (columns, smoke, coins…).
  - Metaphoric scene concepts (not literal illustrations of the narration).
  - Visual bridges between consecutive scenes.
  - Rotating shot types (establishing, detail, mood, action, symbolic).

Architecture
------------
The ``VisualBibleGenerator`` receives a completed script (list of blocks)
and a channel config, builds a specialised system prompt, and calls the
LLM.  If the primary LLM fails it falls back to the same LLM that
generated the script.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from typing import Any, Callable, Optional

logger = logging.getLogger(__name__)

# ── Fallback minimal bible when LLM completely fails ──────────────
FALLBACK_VISUAL_UNIVERSE = (
    "cinematic documentary style, atmospheric lighting, consistent color palette"
)


@dataclass
class VisualBible:
    """Parsed visual direction for a single video."""

    visual_universe: str = FALLBACK_VISUAL_UNIVERSE
    visual_tone_arc: str = "neutral→tense→hopeful"
    central_entity: dict = field(default_factory=lambda: {"type": "none"})
    recurring_elements: list[str] = field(default_factory=list)
    scene_visual_map: list[dict] = field(default_factory=list)

    @classmethod
    def _empty_scene_entry(cls, scene_idx: int) -> dict:
        """Minimal scene-map entry with an EMPTY visual_concept.

        An empty ``visual_concept`` signals the media fetcher to fall back to
        the scene's own ``search_query_en``/``texto`` (or a generic type hint)
        and append ``scene variation {i}/{N}`` for prompt uniqueness.  Reusing
        a non-empty literal here would collapse every scene to the same prompt
        → Pollinations cache returns the same image for all of them.
        """
        return {
            "scene": scene_idx,
            "shot_type": "mood",
            "visual_concept": "",
            "mood": "neutral",
            "has_protagonist": False,
            "bridge_from_prev": None,
            "visual_density": "balanced",
        }

    @classmethod
    def from_dict(cls, data: dict, num_scenes: int = 0) -> "VisualBible":
        """Parse a raw LLM JSON dict into a ``VisualBible``, with fallbacks.

        If the LLM returned fewer ``scene_visual_map`` entries than
        ``num_scenes`` (observed: 11-32 entries for 100-146 scene videos),
        the missing entries are padded with ``_empty_scene_entry`` so the
        fetcher never runs out of per-scene concepts — the empty entries fall
        back to the scene query with a unique ``scene variation`` suffix.
        """
        if not isinstance(data, dict):
            logger.warning("Visual bible LLM returned non-dict; using fallback")
            return cls._fallback(num_scenes)

        scene_map = list(data.get("scene_visual_map") or [])
        if num_scenes > 0 and len(scene_map) < num_scenes:
            logger.warning(
                "Visual bible returned %d/%d scene entries — padding %d with empty concepts",
                len(scene_map), num_scenes, num_scenes - len(scene_map),
            )
            for i in range(len(scene_map), num_scenes):
                scene_map.append(cls._empty_scene_entry(i))

        return cls(
            visual_universe=data.get("visual_universe") or FALLBACK_VISUAL_UNIVERSE,
            visual_tone_arc=data.get("visual_tone_arc") or "neutral→tense→hopeful",
            central_entity=data.get("central_entity") or {"type": "none"},
            recurring_elements=data.get("recurring_elements") or [],
            scene_visual_map=scene_map,
        )

    @classmethod
    def _fallback(cls, num_scenes: int) -> "VisualBible":
        """Return a minimal bible with an empty-concepts scene map.

        Every entry uses an empty ``visual_concept`` so prompt uniqueness is
        delegated to the media fetcher's ``scene variation {i}/{N}`` suffix
        (identical concepts here would all hash to the same cached image).
        """
        scene_map: list[dict] = [cls._empty_scene_entry(i) for i in range(num_scenes)]
        return cls(scene_visual_map=scene_map)

    def to_dict(self) -> dict:
        return {
            "visual_universe": self.visual_universe,
            "visual_tone_arc": self.visual_tone_arc,
            "central_entity": self.central_entity,
            "recurring_elements": self.recurring_elements,
            "scene_visual_map": self.scene_visual_map,
        }


class VisualBibleGenerator:
    """Generate a visual bible by calling the LLM with the completed script.

    Parameters
    ----------
    script_generator:
        The existing ``ScriptGenerator`` instance that owns the LLM client
        pool, JSON parsing, and channel config.  We reuse its
        ``_llm_json_call`` method rather than creating a new client.
    channel_cfg:
        Channel config object (used to build the system prompt).
    """

    def __init__(
        self,
        script_generator: Any,
        channel_cfg: Any,
    ) -> None:
        self._script_gen = script_generator
        self._channel_cfg = channel_cfg

    def generate(
        self,
        script_text: str,
        num_scenes: int,
        model_name: str | None = None,
    ) -> VisualBible:
        """Generate the visual bible for a script.

        Parameters
        ----------
        script_text:
            Full script text (or concatenated block texts) to analyse.
        num_scenes:
            Number of enforceable scenes in the video (used for the
            fallback when the LLM fails).
        model_name:
            Optional model override.  If ``None``, the script generator's
            default model is used.

        Returns
        -------
        VisualBible
            The parsed visual bible, or a minimal fallback on failure.
        """
        from prompts.base_prompts import build_visual_bible_prompt

        system_prompt = build_visual_bible_prompt(self._channel_cfg, num_scenes)
        user_prompt = (
            "Genera la biblia visual para el siguiente guion. "
            "Responde SOLO con el JSON, sin markdown ni explicaciones.\n\n"
            f"GUION:\n---\n{script_text}\n---"
        )

        try:
            logger.info("Generating visual bible for %d scenes...", num_scenes)
            result = None
            last_error = None
            # Reuse the script generator's model pool with proper failover.
            # ``iter_models()`` yields ``(ModelEntry, OpenAI client)`` tuples;
            # pass the client explicitly so we never fall back to the legacy
            # client, and pass the actual model id so the call resolves
            # against the client's own provider.
            for entry, client in self._script_gen.model_pool.iter_models():
                # If a specific model was requested, skip non-matching entries.
                if model_name and model_name not in (entry.model_id, entry.display_name):
                    continue
                try:
                    result = self._script_gen._llm_json_call(
                        thinking=True,
                        client=client,
                        model=entry.model_id,
                        model_name=entry.display_name,
                        messages=[
                            {"role": "system", "content": system_prompt},
                            {"role": "user", "content": user_prompt},
                        ],
                        temperature=0.7,
                    )
                    break
                except Exception as exc:
                    last_error = exc
                    logger.warning(
                        "Visual bible: model %s failed: %s",
                        entry.display_name, exc,
                    )

            if result is None:
                raise last_error if last_error else RuntimeError(
                    "No model available in pool for visual bible"
                )
            bible = VisualBible.from_dict(result, num_scenes)
            logger.info(
                "Visual bible generated: universe=%s..., entity=%s, %d scenes",
                bible.visual_universe[:60],
                bible.central_entity.get("type", "none"),
                len(bible.scene_visual_map),
            )
            return bible

        except Exception as exc:
            logger.warning(
                "Visual bible LLM call failed: %s — using fallback", exc,
            )
            return VisualBible._fallback(num_scenes)
