"""Visual Bible — LLM-generated visual direction for an entire video.

A *visual bible* is a structured JSON blueprint that describes the visual
universe, protagonist, recurring elements, and per-scene visual concepts
for a single video.  It is generated by a second LLM call that analyses
the completed script.

Phase 3 integrates the visual bible into the AI prompt pipeline so that
every generated image shares:
  - A consistent visual universe (time period, location, aesthetic).
  - A stable protagonist description (when the video features a person).
  - Recurring visual motifs (columns, smoke, coins…).
  - Metaphoric scene concepts (not literal illustrations of the narration).
  - Visual bridges between consecutive scenes.
  - Rotating shot types (establishing, detail, mood, action, symbolic).

Architecture
------------
The ``VisualBibleGenerator`` receives a completed script (list of blocks)
and a channel config, builds a specialised system prompt, and calls the
LLM.  If the primary LLM fails it falls back to the same LLM that
generated the script.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from typing import Any, Callable, Optional

logger = logging.getLogger(__name__)

# ── Fallback minimal bible when LLM completely fails ──────────────
FALLBACK_VISUAL_UNIVERSE = (
    "cinematic documentary style, atmospheric lighting, consistent color palette"
)


@dataclass
class VisualBible:
    """Parsed visual direction for a single video."""

    visual_universe: str = FALLBACK_VISUAL_UNIVERSE
    visual_tone_arc: str = "neutral→tense→hopeful"
    central_entity: dict = field(default_factory=lambda: {"type": "none"})
    recurring_elements: list[str] = field(default_factory=list)
    scene_visual_map: list[dict] = field(default_factory=list)

    @classmethod
    def _empty_scene_entry(cls, scene_idx: int) -> dict:
        """Minimal scene-map entry with an EMPTY visual_concept.

        An empty ``visual_concept`` signals the media fetcher to fall back to
        the scene's own ``search_query_en``/``texto`` (or a generic type hint)
        and append ``scene variation {i}/{N}`` for prompt uniqueness.  Reusing
        a non-empty literal here would collapse every scene to the same prompt
        → Pollinations cache returns the same image for all of them.
        """
        return {
            "scene": scene_idx,
            "shot_type": "mood",
            "visual_concept": "",
            "mood": "neutral",
            "has_protagonist": False,
            "bridge_from_prev": None,
            "visual_density": "balanced",
        }

    @classmethod
    def from_dict(cls, data: dict, num_scenes: int = 0) -> "VisualBible":
        """Parse a raw LLM JSON dict into a ``VisualBible``, with fallbacks.

        If the LLM returned fewer ``scene_visual_map`` entries than
        ``num_scenes`` (observed: 11-32 entries for 100-146 scene videos),
        the missing entries are padded with ``_empty_scene_entry`` so the
        fetcher never runs out of per-scene concepts — the empty entries fall
        back to the scene query with a unique ``scene variation`` suffix.
        """
        if not isinstance(data, dict):
            logger.warning("Visual bible LLM returned non-dict; using fallback")
            return cls._fallback(num_scenes)

        scene_map = list(data.get("scene_visual_map") or [])
        if num_scenes > 0 and len(scene_map) < num_scenes:
            logger.warning(
                "Visual bible returned %d/%d scene entries — padding %d with empty concepts",
                len(scene_map), num_scenes, num_scenes - len(scene_map),
            )
            for i in range(len(scene_map), num_scenes):
                scene_map.append(cls._empty_scene_entry(i))

        return cls(
            visual_universe=data.get("visual_universe") or FALLBACK_VISUAL_UNIVERSE,
            visual_tone_arc=data.get("visual_tone_arc") or "neutral→tense→hopeful",
            central_entity=data.get("central_entity") or {"type": "none"},
            recurring_elements=data.get("recurring_elements") or [],
            scene_visual_map=scene_map,
        )

    @classmethod
    def _fallback(cls, num_scenes: int) -> "VisualBible":
        """Return a minimal bible with an empty-concepts scene map.

        Every entry uses an empty ``visual_concept`` so prompt uniqueness is
        delegated to the media fetcher's ``scene variation {i}/{N}`` suffix
        (identical concepts here would all hash to the same cached image).
        """
        scene_map: list[dict] = [cls._empty_scene_entry(i) for i in range(num_scenes)]
        return cls(scene_visual_map=scene_map)

    def to_dict(self) -> dict:
        return {
            "visual_universe": self.visual_universe,
            "visual_tone_arc": self.visual_tone_arc,
            "central_entity": self.central_entity,
            "recurring_elements": self.recurring_elements,
            "scene_visual_map": self.scene_visual_map,
        }

    def with_filled_concepts(self, entries: list[dict]) -> "VisualBible":
        """Return a new bible with freshly generated scene entries merged in.

        Each entry in *entries* is keyed by its ``scene`` index; entries
        without a valid index (or out of range) are ignored.  The merge
        preserves the original bible's universe/tone/entity/elements and
        only replaces the per-scene fields of the recovered scenes.
        """
        by_scene: dict[int, dict] = {}
        for entry in entries:
            try:
                sidx = int(entry.get("scene", -1))
            except (TypeError, ValueError):
                sidx = -1
            if sidx >= 0:
                by_scene[sidx] = entry

        merged = [dict(e) for e in self.scene_visual_map]
        for sidx, entry in by_scene.items():
            if 0 <= sidx < len(merged):
                merged[sidx] = {**merged[sidx], **entry}

        return VisualBible(
            visual_universe=self.visual_universe,
            visual_tone_arc=self.visual_tone_arc,
            central_entity=self.central_entity,
            recurring_elements=self.recurring_elements,
            scene_visual_map=merged,
        )


class VisualBibleGenerator:
    """Generate a visual bible by calling the LLM with the completed script.

    Parameters
    ----------
    script_generator:
        The existing ``ScriptGenerator`` instance that owns the LLM client
        pool, JSON parsing, and channel config.  We reuse its
        ``_llm_json_call`` method rather than creating a new client.
    channel_cfg:
        Channel config object (used to build the system prompt).
    """

    def __init__(
        self,
        script_generator: Any,
        channel_cfg: Any,
    ) -> None:
        self._script_gen = script_generator
        self._channel_cfg = channel_cfg

    def generate(
        self,
        script_text: str,
        num_scenes: int,
        model_name: str | None = None,
    ) -> VisualBible:
        """Generate the visual bible for a script.

        Parameters
        ----------
        script_text:
            Full script text (or concatenated block texts) to analyse.
        num_scenes:
            Number of enforceable scenes in the video (used for the
            fallback when the LLM fails).
        model_name:
            Optional model override.  If ``None``, the script generator's
            default model is used.

        Returns
        -------
        VisualBible
            The parsed visual bible, or a minimal fallback on failure.
        """
        from prompts.base_prompts import build_visual_bible_prompt

        system_prompt = build_visual_bible_prompt(self._channel_cfg, num_scenes)
        user_prompt = (
            "Genera la biblia visual para el siguiente guion. "
            "Responde SOLO con el JSON, sin markdown ni explicaciones.\n\n"
            f"GUION:\n---\n{script_text}\n---"
        )

        try:
            logger.info("Generating visual bible for %d scenes...", num_scenes)
            result = None
            last_error = None
            # Reuse the script generator's model pool with proper failover.
            # ``iter_models()`` yields ``(ModelEntry, OpenAI client)`` tuples;
            # pass the client explicitly so we never fall back to the legacy
            # client, and pass the actual model id so the call resolves
            # against the client's own provider.
            for entry, client in self._script_gen.model_pool.iter_models():
                # If a specific model was requested, skip non-matching entries.
                if model_name and model_name not in (entry.model_id, entry.display_name):
                    continue
                try:
                    result = self._script_gen._llm_json_call(
                        thinking=True,
                        client=client,
                        model=entry.model_id,
                        model_name=entry.display_name,
                        messages=[
                            {"role": "system", "content": system_prompt},
                            {"role": "user", "content": user_prompt},
                        ],
                        temperature=0.7,
                    )
                    break
                except Exception as exc:
                    last_error = exc
                    logger.warning(
                        "Visual bible: model %s failed: %s",
                        entry.display_name, exc,
                    )

            if result is None:
                raise last_error if last_error else RuntimeError(
                    "No model available in pool for visual bible"
                )
            bible = VisualBible.from_dict(result, num_scenes)
        except Exception as exc:
            logger.warning(
                "Visual bible LLM call failed: %s — using fallback", exc,
            )
            bible = VisualBible._fallback(num_scenes)

        # ── Gap fill: regenerate missing/empty scene concepts ──────────
        # A partial or empty bible leaves scenes without a visual_concept;
        # those scenes then collapse to generic prompts → Pollinations
        # returns the same cached image for all of them → render-time
        # dedup rejects the duplicates → placeholder cascade → assembly
        # abort.  Try ONE targeted regeneration of the missing concepts
        # before degrading to empty entries (which the media fetcher pads).
        missing = [
            i for i, e in enumerate(bible.scene_visual_map)
            if not (e.get("visual_concept") or "").strip()
        ]
        if missing and len(missing) >= max(3, int(num_scenes * 0.05)):
            logger.info(
                "Visual bible: %d/%d scenes lack concepts — regenerating...",
                len(missing), num_scenes,
            )
            filled = self._generate_missing_concepts(
                script_text, missing, num_scenes, model_name,
            )
            if filled:
                bible = bible.with_filled_concepts(filled)
                still_missing = [
                    i for i, e in enumerate(bible.scene_visual_map)
                    if not (e.get("visual_concept") or "").strip()
                ]
                logger.info(
                    "Visual bible gap fill: recovered %d/%d concepts, "
                    "%d still empty (will use scene queries)",
                    len(filled) - len(still_missing),
                    len(missing), len(still_missing),
                )

        logger.info(
            "Visual bible generated: universe=%s..., entity=%s, %d scenes",
            bible.visual_universe[:60],
            bible.central_entity.get("type", "none"),
            len(bible.scene_visual_map),
        )
        return bible

    def _generate_missing_concepts(
        self,
        script_text: str,
        missing_indices: list[int],
        num_scenes: int,
        model_name: str | None = None,
    ) -> list[dict]:
        """Second, targeted LLM call that generates ONLY the missing concepts.

        Reuses the same model pool/failover as the main call.  Returns a
        list of scene-map entries (dicts) that have a valid ``scene`` index
        and a non-empty ``visual_concept``; empty list on total failure.
        """
        missing_list = ", ".join(str(i) for i in missing_indices)
        system_prompt = (
            "Eres un director de fotografia y diseno visual experto en documentales.\n"
            "Una biblia visual previa omitio los conceptos visuales de algunas escenas.\n"
            "Tu tarea: generar SOLO los conceptos faltantes, manteniendo coherencia\n"
            "con el universo visual del guion.\n\n"
            "REGLA: METAFORA VISUAL, NO LITERAL. No describas la narracion al pie\n"
            "de la letra; crea una imagen que transmita la misma emocion. visual_concept\n"
            "debe estar en INGLES. JAMAS muestres texto en la imagen.\n\n"
            "FORMATO: Responde EXCLUSIVAMENTE con un JSON valido, sin markdown:\n"
            '{"scene_visual_map": [{"scene": <indice>, "shot_type": "mood|detail|establishing|action|symbolic", '
            '"visual_concept": "<concepto en ingles>", "mood": "<emocion>", '
            '"has_protagonist": false, "bridge_from_prev": null, '
            '"visual_density": "simple|balanced|rich"}]}'
        )
        user_prompt = (
            f"Faltan los conceptos visuales de las escenas con indices: "
            f"[{missing_list}] (de un total de {num_scenes} escenas).\n"
            "Genera UNA entrada por escena faltante, cada una con su indice exacto.\n\n"
            f"GUION:\n---\n{script_text}\n---"
        )

        result = None
        for entry, client in self._script_gen.model_pool.iter_models():
            if model_name and model_name not in (entry.model_id, entry.display_name):
                continue
            try:
                result = self._script_gen._llm_json_call(
                    thinking=True,
                    client=client,
                    model=entry.model_id,
                    model_name=entry.display_name,
                    messages=[
                        {"role": "system", "content": system_prompt},
                        {"role": "user", "content": user_prompt},
                    ],
                    temperature=0.7,
                )
                break
            except Exception as exc:
                logger.warning(
                    "Visual bible gap fill: model %s failed: %s",
                    entry.display_name, exc,
                )

        if isinstance(result, dict):
            entries = result.get("scene_visual_map") or []
            if isinstance(entries, list):
                valid = [
                    e for e in entries
                    if isinstance(e, dict)
                    and (e.get("visual_concept") or "").strip()
                ]
                if valid:
                    return valid
        logger.warning(
            "Visual bible gap fill failed — %d scenes stay without concepts",
            len(missing_indices),
        )
        return []
