"""Visual Bible — LLM-generated visual direction for an entire video.

A *visual bible* is a structured JSON blueprint that describes the visual
universe, protagonist, recurring elements, and per-scene visual concepts
for a single video.  It is generated by a second LLM call that analyses
the completed script.

Phase 3 integrates the visual bible into the AI prompt pipeline so that
every generated image shares:
  - A consistent visual universe (time period, location, aesthetic).
  - A stable protagonist description (when the video features a person).
  - Recurring visual motifs (columns, smoke, coins…).
  - Metaphoric scene concepts (not literal illustrations of the narration).
  - Visual bridges between consecutive scenes.
  - Rotating shot types (establishing, detail, mood, action, symbolic).

Architecture
------------
The ``VisualBibleGenerator`` receives a completed script (list of blocks)
and a channel config, builds a specialised system prompt, and calls the
LLM.  If the primary LLM fails it falls back to the same LLM that
generated the script.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from typing import Any, Callable, Optional

logger = logging.getLogger(__name__)

# ── Fallback minimal bible when LLM completely fails ──────────────
FALLBACK_VISUAL_UNIVERSE = (
    "cinematic documentary style, atmospheric lighting, consistent color palette"
)


@dataclass
class VisualBible:
    """Parsed visual direction for a single video."""

    visual_universe: str = FALLBACK_VISUAL_UNIVERSE
    visual_tone_arc: str = "neutral→tense→hopeful"
    central_entity: dict = field(default_factory=lambda: {"type": "none"})
    recurring_elements: list[str] = field(default_factory=list)
    scene_visual_map: list[dict] = field(default_factory=list)

    @classmethod
    def from_dict(cls, data: dict, num_scenes: int = 0) -> "VisualBible":
        """Parse a raw LLM JSON dict into a ``VisualBible``, with fallbacks."""
        if not isinstance(data, dict):
            logger.warning("Visual bible LLM returned non-dict; using fallback")
            return cls._fallback(num_scenes)

        return cls(
            visual_universe=data.get("visual_universe") or FALLBACK_VISUAL_UNIVERSE,
            visual_tone_arc=data.get("visual_tone_arc") or "neutral→tense→hopeful",
            central_entity=data.get("central_entity") or {"type": "none"},
            recurring_elements=data.get("recurring_elements") or [],
            scene_visual_map=data.get("scene_visual_map") or [],
        )

    @classmethod
    def _fallback(cls, num_scenes: int) -> "VisualBible":
        """Return a minimal bible with a generic scene map."""
        scene_map: list[dict] = []
        for i in range(num_scenes):
            scene_map.append({
                "scene": i,
                "shot_type": "mood",
                "visual_concept": "cinematic atmospheric documentary scene",
                "mood": "neutral",
                "has_protagonist": False,
                "bridge_from_prev": None,
                "visual_density": "balanced",
            })
        return cls(scene_visual_map=scene_map)

    def to_dict(self) -> dict:
        return {
            "visual_universe": self.visual_universe,
            "visual_tone_arc": self.visual_tone_arc,
            "central_entity": self.central_entity,
            "recurring_elements": self.recurring_elements,
            "scene_visual_map": self.scene_visual_map,
        }


class VisualBibleGenerator:
    """Generate a visual bible by calling the LLM with the completed script.

    Parameters
    ----------
    script_generator:
        The existing ``ScriptGenerator`` instance that owns the LLM client
        pool, JSON parsing, and channel config.  We reuse its
        ``_llm_json_call`` method rather than creating a new client.
    channel_cfg:
        Channel config object (used to build the system prompt).
    """

    def __init__(
        self,
        script_generator: Any,
        channel_cfg: Any,
    ) -> None:
        self._script_gen = script_generator
        self._channel_cfg = channel_cfg

    def generate(
        self,
        script_text: str,
        num_scenes: int,
        model_name: str | None = None,
    ) -> VisualBible:
        """Generate the visual bible for a script.

        Parameters
        ----------
        script_text:
            Full script text (or concatenated block texts) to analyse.
        num_scenes:
            Number of enforceable scenes in the video (used for the
            fallback when the LLM fails).
        model_name:
            Optional model override.  If ``None``, the script generator's
            default model is used.

        Returns
        -------
        VisualBible
            The parsed visual bible, or a minimal fallback on failure.
        """
        from prompts.base_prompts import build_visual_bible_prompt

        system_prompt = build_visual_bible_prompt(self._channel_cfg, num_scenes)
        user_prompt = (
            "Genera la biblia visual para el siguiente guion. "
            "Responde SOLO con el JSON, sin markdown ni explicaciones.\n\n"
            f"GUION:\n---\n{script_text}\n---"
        )

        try:
            logger.info("Generating visual bible for %d scenes...", num_scenes)
            # Determine which model to use
            model = model_name
            if not model:
                # Fall back to the script generator's first pool model
                try:
                    for entry in self._script_gen.model_pool.iter_models():
                        model = entry.model_id
                        break
                except Exception:
                    model = "gpt-4o-mini"  # absolute fallback

            result = self._script_gen._llm_json_call(
                thinking=True,
                model=model,
                model_name=model or "visual-bible",
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                temperature=0.7,
            )
            bible = VisualBible.from_dict(result, num_scenes)
            logger.info(
                "Visual bible generated: universe=%s..., entity=%s, %d scenes",
                bible.visual_universe[:60],
                bible.central_entity.get("type", "none"),
                len(bible.scene_visual_map),
            )
            return bible

        except Exception as exc:
            logger.warning(
                "Visual bible LLM call failed: %s — using fallback", exc,
            )
            return VisualBible._fallback(num_scenes)
